version: "3.3"

networks: 
  microsservices-template:
    name: microsservices-template

services:

  config-server:
    container_name: microsservice-config-server
    build:
      context: config-server/
      args: 
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_PASS: ${GITHUB_PASS}
    ports:
      - "8888:8888"
    environment:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASS=${GITHUB_PASS}
    networks:
      - microsservices-template

  service-discovery:
    container_name: microsservice-service-discovery
    build:
      context: service-discovery/
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - microsservices-template
  
  user:
    container_name: microsservice-user
    build:
      context: user/
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        AUTH_EMAIL: ${AUTH_EMAIL}
        AUTH_NAME: ${AUTH_NAME}
        AUTH_PASS: ${AUTH_PASS}
    depends_on:
      - config-server
      - service-discovery
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_EMAIL=${AUTH_EMAIL}
      - AUTH_NAME=${AUTH_NAME}
      - AUTH_PASS=${AUTH_PASS}
    networks:
      - microsservices-template
    #command: docker run -p --network microsservices-template user:v1

  authentication:
    container_name: authentication
    build:
      context: authentication/
    depends_on: 
      - config-server
      - service-discovery
      - user
    networks:
      - microsservices-template
  
  gateway:
    container_name: gateway
    build:
      context: gateway/
    depends_on:
      - config-server
      - service-discovery
      - user
      - authentication
    ports:
      - "8765:8765"
    networks:
      - microsservices-template

  #authentication:
  #  container_name: microsservice-authentication
  #  build: authentication/
  #  ports:
  #    - "8761:8761"
  #  depends_on:
  #    - config-server